// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/attention-controller/pkg"
)

type AttentionStore struct {
	AnswerStub        func(context.Context, pkg.ItemID, string) (*pkg.Item, error)
	answerMutex       sync.RWMutex
	answerArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.ItemID
		arg3 string
	}
	answerReturns struct {
		result1 *pkg.Item
		result2 error
	}
	answerReturnsOnCall map[int]struct {
		result1 *pkg.Item
		result2 error
	}
	CloseStub        func(context.Context, pkg.ItemID) (*pkg.Item, error)
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.ItemID
	}
	closeReturns struct {
		result1 *pkg.Item
		result2 error
	}
	closeReturnsOnCall map[int]struct {
		result1 *pkg.Item
		result2 error
	}
	EscalateStub        func(context.Context, pkg.ItemID, string) (*pkg.Item, error)
	escalateMutex       sync.RWMutex
	escalateArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.ItemID
		arg3 string
	}
	escalateReturns struct {
		result1 *pkg.Item
		result2 error
	}
	escalateReturnsOnCall map[int]struct {
		result1 *pkg.Item
		result2 error
	}
	GetStub        func(context.Context, pkg.ItemID) (*pkg.Item, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.ItemID
	}
	getReturns struct {
		result1 *pkg.Item
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 *pkg.Item
		result2 error
	}
	PushStub        func(context.Context, pkg.PushRequest) (*pkg.Item, error)
	pushMutex       sync.RWMutex
	pushArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.PushRequest
	}
	pushReturns struct {
		result1 *pkg.Item
		result2 error
	}
	pushReturnsOnCall map[int]struct {
		result1 *pkg.Item
		result2 error
	}
	ReadStub        func(context.Context) (pkg.Items, error)
	readMutex       sync.RWMutex
	readArgsForCall []struct {
		arg1 context.Context
	}
	readReturns struct {
		result1 pkg.Items
		result2 error
	}
	readReturnsOnCall map[int]struct {
		result1 pkg.Items
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *AttentionStore) Answer(arg1 context.Context, arg2 pkg.ItemID, arg3 string) (*pkg.Item, error) {
	fake.answerMutex.Lock()
	ret, specificReturn := fake.answerReturnsOnCall[len(fake.answerArgsForCall)]
	fake.answerArgsForCall = append(fake.answerArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.ItemID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.AnswerStub
	fakeReturns := fake.answerReturns
	fake.recordInvocation("Answer", []interface{}{arg1, arg2, arg3})
	fake.answerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AttentionStore) AnswerCallCount() int {
	fake.answerMutex.RLock()
	defer fake.answerMutex.RUnlock()
	return len(fake.answerArgsForCall)
}

func (fake *AttentionStore) AnswerCalls(stub func(context.Context, pkg.ItemID, string) (*pkg.Item, error)) {
	fake.answerMutex.Lock()
	defer fake.answerMutex.Unlock()
	fake.AnswerStub = stub
}

func (fake *AttentionStore) AnswerArgsForCall(i int) (context.Context, pkg.ItemID, string) {
	fake.answerMutex.RLock()
	defer fake.answerMutex.RUnlock()
	argsForCall := fake.answerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *AttentionStore) AnswerReturns(result1 *pkg.Item, result2 error) {
	fake.answerMutex.Lock()
	defer fake.answerMutex.Unlock()
	fake.AnswerStub = nil
	fake.answerReturns = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *AttentionStore) AnswerReturnsOnCall(i int, result1 *pkg.Item, result2 error) {
	fake.answerMutex.Lock()
	defer fake.answerMutex.Unlock()
	fake.AnswerStub = nil
	if fake.answerReturnsOnCall == nil {
		fake.answerReturnsOnCall = make(map[int]struct {
			result1 *pkg.Item
			result2 error
		})
	}
	fake.answerReturnsOnCall[i] = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *AttentionStore) Close(arg1 context.Context, arg2 pkg.ItemID) (*pkg.Item, error) {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.ItemID
	}{arg1, arg2})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{arg1, arg2})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AttentionStore) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *AttentionStore) CloseCalls(stub func(context.Context, pkg.ItemID) (*pkg.Item, error)) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *AttentionStore) CloseArgsForCall(i int) (context.Context, pkg.ItemID) {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	argsForCall := fake.closeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *AttentionStore) CloseReturns(result1 *pkg.Item, result2 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *AttentionStore) CloseReturnsOnCall(i int, result1 *pkg.Item, result2 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 *pkg.Item
			result2 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *AttentionStore) Escalate(arg1 context.Context, arg2 pkg.ItemID, arg3 string) (*pkg.Item, error) {
	fake.escalateMutex.Lock()
	ret, specificReturn := fake.escalateReturnsOnCall[len(fake.escalateArgsForCall)]
	fake.escalateArgsForCall = append(fake.escalateArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.ItemID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.EscalateStub
	fakeReturns := fake.escalateReturns
	fake.recordInvocation("Escalate", []interface{}{arg1, arg2, arg3})
	fake.escalateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AttentionStore) EscalateCallCount() int {
	fake.escalateMutex.RLock()
	defer fake.escalateMutex.RUnlock()
	return len(fake.escalateArgsForCall)
}

func (fake *AttentionStore) EscalateCalls(stub func(context.Context, pkg.ItemID, string) (*pkg.Item, error)) {
	fake.escalateMutex.Lock()
	defer fake.escalateMutex.Unlock()
	fake.EscalateStub = stub
}

func (fake *AttentionStore) EscalateArgsForCall(i int) (context.Context, pkg.ItemID, string) {
	fake.escalateMutex.RLock()
	defer fake.escalateMutex.RUnlock()
	argsForCall := fake.escalateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *AttentionStore) EscalateReturns(result1 *pkg.Item, result2 error) {
	fake.escalateMutex.Lock()
	defer fake.escalateMutex.Unlock()
	fake.EscalateStub = nil
	fake.escalateReturns = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *AttentionStore) EscalateReturnsOnCall(i int, result1 *pkg.Item, result2 error) {
	fake.escalateMutex.Lock()
	defer fake.escalateMutex.Unlock()
	fake.EscalateStub = nil
	if fake.escalateReturnsOnCall == nil {
		fake.escalateReturnsOnCall = make(map[int]struct {
			result1 *pkg.Item
			result2 error
		})
	}
	fake.escalateReturnsOnCall[i] = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *AttentionStore) Get(arg1 context.Context, arg2 pkg.ItemID) (*pkg.Item, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.ItemID
	}{arg1, arg2})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1, arg2})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AttentionStore) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *AttentionStore) GetCalls(stub func(context.Context, pkg.ItemID) (*pkg.Item, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *AttentionStore) GetArgsForCall(i int) (context.Context, pkg.ItemID) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *AttentionStore) GetReturns(result1 *pkg.Item, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *AttentionStore) GetReturnsOnCall(i int, result1 *pkg.Item, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *pkg.Item
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *AttentionStore) Push(arg1 context.Context, arg2 pkg.PushRequest) (*pkg.Item, error) {
	fake.pushMutex.Lock()
	ret, specificReturn := fake.pushReturnsOnCall[len(fake.pushArgsForCall)]
	fake.pushArgsForCall = append(fake.pushArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.PushRequest
	}{arg1, arg2})
	stub := fake.PushStub
	fakeReturns := fake.pushReturns
	fake.recordInvocation("Push", []interface{}{arg1, arg2})
	fake.pushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AttentionStore) PushCallCount() int {
	fake.pushMutex.RLock()
	defer fake.pushMutex.RUnlock()
	return len(fake.pushArgsForCall)
}

func (fake *AttentionStore) PushCalls(stub func(context.Context, pkg.PushRequest) (*pkg.Item, error)) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = stub
}

func (fake *AttentionStore) PushArgsForCall(i int) (context.Context, pkg.PushRequest) {
	fake.pushMutex.RLock()
	defer fake.pushMutex.RUnlock()
	argsForCall := fake.pushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *AttentionStore) PushReturns(result1 *pkg.Item, result2 error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = nil
	fake.pushReturns = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *AttentionStore) PushReturnsOnCall(i int, result1 *pkg.Item, result2 error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = nil
	if fake.pushReturnsOnCall == nil {
		fake.pushReturnsOnCall = make(map[int]struct {
			result1 *pkg.Item
			result2 error
		})
	}
	fake.pushReturnsOnCall[i] = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *AttentionStore) Read(arg1 context.Context) (pkg.Items, error) {
	fake.readMutex.Lock()
	ret, specificReturn := fake.readReturnsOnCall[len(fake.readArgsForCall)]
	fake.readArgsForCall = append(fake.readArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ReadStub
	fakeReturns := fake.readReturns
	fake.recordInvocation("Read", []interface{}{arg1})
	fake.readMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AttentionStore) ReadCallCount() int {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	return len(fake.readArgsForCall)
}

func (fake *AttentionStore) ReadCalls(stub func(context.Context) (pkg.Items, error)) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = stub
}

func (fake *AttentionStore) ReadArgsForCall(i int) context.Context {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	argsForCall := fake.readArgsForCall[i]
	return argsForCall.arg1
}

func (fake *AttentionStore) ReadReturns(result1 pkg.Items, result2 error) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = nil
	fake.readReturns = struct {
		result1 pkg.Items
		result2 error
	}{result1, result2}
}

func (fake *AttentionStore) ReadReturnsOnCall(i int, result1 pkg.Items, result2 error) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = nil
	if fake.readReturnsOnCall == nil {
		fake.readReturnsOnCall = make(map[int]struct {
			result1 pkg.Items
			result2 error
		})
	}
	fake.readReturnsOnCall[i] = struct {
		result1 pkg.Items
		result2 error
	}{result1, result2}
}

func (fake *AttentionStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *AttentionStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.AttentionStore = new(AttentionStore)
