// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/attention-controller/pkg"
)

type AttentionChangeNotifier struct {
	GenerationStub        func() uint64
	generationMutex       sync.RWMutex
	generationArgsForCall []struct {
	}
	generationReturns struct {
		result1 uint64
	}
	generationReturnsOnCall map[int]struct {
		result1 uint64
	}
	NotifyStub        func()
	notifyMutex       sync.RWMutex
	notifyArgsForCall []struct {
	}
	SubscribeStub        func() (<-chan struct{}, func())
	subscribeMutex       sync.RWMutex
	subscribeArgsForCall []struct {
	}
	subscribeReturns struct {
		result1 <-chan struct{}
		result2 func()
	}
	subscribeReturnsOnCall map[int]struct {
		result1 <-chan struct{}
		result2 func()
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *AttentionChangeNotifier) Generation() uint64 {
	fake.generationMutex.Lock()
	ret, specificReturn := fake.generationReturnsOnCall[len(fake.generationArgsForCall)]
	fake.generationArgsForCall = append(fake.generationArgsForCall, struct {
	}{})
	stub := fake.GenerationStub
	fakeReturns := fake.generationReturns
	fake.recordInvocation("Generation", []interface{}{})
	fake.generationMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *AttentionChangeNotifier) GenerationCallCount() int {
	fake.generationMutex.RLock()
	defer fake.generationMutex.RUnlock()
	return len(fake.generationArgsForCall)
}

func (fake *AttentionChangeNotifier) GenerationCalls(stub func() uint64) {
	fake.generationMutex.Lock()
	defer fake.generationMutex.Unlock()
	fake.GenerationStub = stub
}

func (fake *AttentionChangeNotifier) GenerationReturns(result1 uint64) {
	fake.generationMutex.Lock()
	defer fake.generationMutex.Unlock()
	fake.GenerationStub = nil
	fake.generationReturns = struct {
		result1 uint64
	}{result1}
}

func (fake *AttentionChangeNotifier) GenerationReturnsOnCall(i int, result1 uint64) {
	fake.generationMutex.Lock()
	defer fake.generationMutex.Unlock()
	fake.GenerationStub = nil
	if fake.generationReturnsOnCall == nil {
		fake.generationReturnsOnCall = make(map[int]struct {
			result1 uint64
		})
	}
	fake.generationReturnsOnCall[i] = struct {
		result1 uint64
	}{result1}
}

func (fake *AttentionChangeNotifier) Notify() {
	fake.notifyMutex.Lock()
	fake.notifyArgsForCall = append(fake.notifyArgsForCall, struct {
	}{})
	stub := fake.NotifyStub
	fake.recordInvocation("Notify", []interface{}{})
	fake.notifyMutex.Unlock()
	if stub != nil {
		fake.NotifyStub()
	}
}

func (fake *AttentionChangeNotifier) NotifyCallCount() int {
	fake.notifyMutex.RLock()
	defer fake.notifyMutex.RUnlock()
	return len(fake.notifyArgsForCall)
}

func (fake *AttentionChangeNotifier) NotifyCalls(stub func()) {
	fake.notifyMutex.Lock()
	defer fake.notifyMutex.Unlock()
	fake.NotifyStub = stub
}

func (fake *AttentionChangeNotifier) Subscribe() (<-chan struct{}, func()) {
	fake.subscribeMutex.Lock()
	ret, specificReturn := fake.subscribeReturnsOnCall[len(fake.subscribeArgsForCall)]
	fake.subscribeArgsForCall = append(fake.subscribeArgsForCall, struct {
	}{})
	stub := fake.SubscribeStub
	fakeReturns := fake.subscribeReturns
	fake.recordInvocation("Subscribe", []interface{}{})
	fake.subscribeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AttentionChangeNotifier) SubscribeCallCount() int {
	fake.subscribeMutex.RLock()
	defer fake.subscribeMutex.RUnlock()
	return len(fake.subscribeArgsForCall)
}

func (fake *AttentionChangeNotifier) SubscribeCalls(stub func() (<-chan struct{}, func())) {
	fake.subscribeMutex.Lock()
	defer fake.subscribeMutex.Unlock()
	fake.SubscribeStub = stub
}

func (fake *AttentionChangeNotifier) SubscribeReturns(result1 <-chan struct{}, result2 func()) {
	fake.subscribeMutex.Lock()
	defer fake.subscribeMutex.Unlock()
	fake.SubscribeStub = nil
	fake.subscribeReturns = struct {
		result1 <-chan struct{}
		result2 func()
	}{result1, result2}
}

func (fake *AttentionChangeNotifier) SubscribeReturnsOnCall(i int, result1 <-chan struct{}, result2 func()) {
	fake.subscribeMutex.Lock()
	defer fake.subscribeMutex.Unlock()
	fake.SubscribeStub = nil
	if fake.subscribeReturnsOnCall == nil {
		fake.subscribeReturnsOnCall = make(map[int]struct {
			result1 <-chan struct{}
			result2 func()
		})
	}
	fake.subscribeReturnsOnCall[i] = struct {
		result1 <-chan struct{}
		result2 func()
	}{result1, result2}
}

func (fake *AttentionChangeNotifier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *AttentionChangeNotifier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.AttentionChangeNotifier = new(AttentionChangeNotifier)
