// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/attention-controller/pkg"
)

type JumpCaller struct {
	JumpStub        func(context.Context, string, string, string) error
	jumpMutex       sync.RWMutex
	jumpArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	jumpReturns struct {
		result1 error
	}
	jumpReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *JumpCaller) Jump(arg1 context.Context, arg2 string, arg3 string, arg4 string) error {
	fake.jumpMutex.Lock()
	ret, specificReturn := fake.jumpReturnsOnCall[len(fake.jumpArgsForCall)]
	fake.jumpArgsForCall = append(fake.jumpArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.JumpStub
	fakeReturns := fake.jumpReturns
	fake.recordInvocation("Jump", []interface{}{arg1, arg2, arg3, arg4})
	fake.jumpMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *JumpCaller) JumpCallCount() int {
	fake.jumpMutex.RLock()
	defer fake.jumpMutex.RUnlock()
	return len(fake.jumpArgsForCall)
}

func (fake *JumpCaller) JumpCalls(stub func(context.Context, string, string, string) error) {
	fake.jumpMutex.Lock()
	defer fake.jumpMutex.Unlock()
	fake.JumpStub = stub
}

func (fake *JumpCaller) JumpArgsForCall(i int) (context.Context, string, string, string) {
	fake.jumpMutex.RLock()
	defer fake.jumpMutex.RUnlock()
	argsForCall := fake.jumpArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *JumpCaller) JumpReturns(result1 error) {
	fake.jumpMutex.Lock()
	defer fake.jumpMutex.Unlock()
	fake.JumpStub = nil
	fake.jumpReturns = struct {
		result1 error
	}{result1}
}

func (fake *JumpCaller) JumpReturnsOnCall(i int, result1 error) {
	fake.jumpMutex.Lock()
	defer fake.jumpMutex.Unlock()
	fake.JumpStub = nil
	if fake.jumpReturnsOnCall == nil {
		fake.jumpReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.jumpReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *JumpCaller) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *JumpCaller) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.JumpCaller = new(JumpCaller)
