// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/attention-controller/pkg"
)

type Metrics struct {
	BoardPageRequestsTotalCounterIncStub        func()
	boardPageRequestsTotalCounterIncMutex       sync.RWMutex
	boardPageRequestsTotalCounterIncArgsForCall []struct {
	}
	BoardRendersTotalCounterIncStub        func()
	boardRendersTotalCounterIncMutex       sync.RWMutex
	boardRendersTotalCounterIncArgsForCall []struct {
	}
	BoardRowsRenderedTotalCounterAddStub        func(int)
	boardRowsRenderedTotalCounterAddMutex       sync.RWMutex
	boardRowsRenderedTotalCounterAddArgsForCall []struct {
		arg1 int
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Metrics) BoardPageRequestsTotalCounterInc() {
	fake.boardPageRequestsTotalCounterIncMutex.Lock()
	fake.boardPageRequestsTotalCounterIncArgsForCall = append(fake.boardPageRequestsTotalCounterIncArgsForCall, struct {
	}{})
	stub := fake.BoardPageRequestsTotalCounterIncStub
	fake.recordInvocation("BoardPageRequestsTotalCounterInc", []interface{}{})
	fake.boardPageRequestsTotalCounterIncMutex.Unlock()
	if stub != nil {
		fake.BoardPageRequestsTotalCounterIncStub()
	}
}

func (fake *Metrics) BoardPageRequestsTotalCounterIncCallCount() int {
	fake.boardPageRequestsTotalCounterIncMutex.RLock()
	defer fake.boardPageRequestsTotalCounterIncMutex.RUnlock()
	return len(fake.boardPageRequestsTotalCounterIncArgsForCall)
}

func (fake *Metrics) BoardPageRequestsTotalCounterIncCalls(stub func()) {
	fake.boardPageRequestsTotalCounterIncMutex.Lock()
	defer fake.boardPageRequestsTotalCounterIncMutex.Unlock()
	fake.BoardPageRequestsTotalCounterIncStub = stub
}

func (fake *Metrics) BoardRendersTotalCounterInc() {
	fake.boardRendersTotalCounterIncMutex.Lock()
	fake.boardRendersTotalCounterIncArgsForCall = append(fake.boardRendersTotalCounterIncArgsForCall, struct {
	}{})
	stub := fake.BoardRendersTotalCounterIncStub
	fake.recordInvocation("BoardRendersTotalCounterInc", []interface{}{})
	fake.boardRendersTotalCounterIncMutex.Unlock()
	if stub != nil {
		fake.BoardRendersTotalCounterIncStub()
	}
}

func (fake *Metrics) BoardRendersTotalCounterIncCallCount() int {
	fake.boardRendersTotalCounterIncMutex.RLock()
	defer fake.boardRendersTotalCounterIncMutex.RUnlock()
	return len(fake.boardRendersTotalCounterIncArgsForCall)
}

func (fake *Metrics) BoardRendersTotalCounterIncCalls(stub func()) {
	fake.boardRendersTotalCounterIncMutex.Lock()
	defer fake.boardRendersTotalCounterIncMutex.Unlock()
	fake.BoardRendersTotalCounterIncStub = stub
}

func (fake *Metrics) BoardRowsRenderedTotalCounterAdd(arg1 int) {
	fake.boardRowsRenderedTotalCounterAddMutex.Lock()
	fake.boardRowsRenderedTotalCounterAddArgsForCall = append(fake.boardRowsRenderedTotalCounterAddArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.BoardRowsRenderedTotalCounterAddStub
	fake.recordInvocation("BoardRowsRenderedTotalCounterAdd", []interface{}{arg1})
	fake.boardRowsRenderedTotalCounterAddMutex.Unlock()
	if stub != nil {
		fake.BoardRowsRenderedTotalCounterAddStub(arg1)
	}
}

func (fake *Metrics) BoardRowsRenderedTotalCounterAddCallCount() int {
	fake.boardRowsRenderedTotalCounterAddMutex.RLock()
	defer fake.boardRowsRenderedTotalCounterAddMutex.RUnlock()
	return len(fake.boardRowsRenderedTotalCounterAddArgsForCall)
}

func (fake *Metrics) BoardRowsRenderedTotalCounterAddCalls(stub func(int)) {
	fake.boardRowsRenderedTotalCounterAddMutex.Lock()
	defer fake.boardRowsRenderedTotalCounterAddMutex.Unlock()
	fake.BoardRowsRenderedTotalCounterAddStub = stub
}

func (fake *Metrics) BoardRowsRenderedTotalCounterAddArgsForCall(i int) int {
	fake.boardRowsRenderedTotalCounterAddMutex.RLock()
	defer fake.boardRowsRenderedTotalCounterAddMutex.RUnlock()
	argsForCall := fake.boardRowsRenderedTotalCounterAddArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Metrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.Metrics = new(Metrics)
