// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/attention-controller/pkg"
)

type RemoteAttentionStore struct {
	AnswerStub        func(context.Context, pkg.ItemID, string, string, pkg.Decision, *pkg.Answer, pkg.Answers, *pkg.AnsweredClient) (*pkg.Item, error)
	answerMutex       sync.RWMutex
	answerArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.ItemID
		arg3 string
		arg4 string
		arg5 pkg.Decision
		arg6 *pkg.Answer
		arg7 pkg.Answers
		arg8 *pkg.AnsweredClient
	}
	answerReturns struct {
		result1 *pkg.Item
		result2 error
	}
	answerReturnsOnCall map[int]struct {
		result1 *pkg.Item
		result2 error
	}
	CloseStub        func(context.Context, pkg.ItemID, string, *pkg.AnsweredClient) (*pkg.Item, error)
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.ItemID
		arg3 string
		arg4 *pkg.AnsweredClient
	}
	closeReturns struct {
		result1 *pkg.Item
		result2 error
	}
	closeReturnsOnCall map[int]struct {
		result1 *pkg.Item
		result2 error
	}
	EscalateStub        func(context.Context, pkg.ItemID, string) (*pkg.Item, error)
	escalateMutex       sync.RWMutex
	escalateArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.ItemID
		arg3 string
	}
	escalateReturns struct {
		result1 *pkg.Item
		result2 error
	}
	escalateReturnsOnCall map[int]struct {
		result1 *pkg.Item
		result2 error
	}
	GetStub        func(context.Context, pkg.ItemID) (*pkg.Item, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.ItemID
	}
	getReturns struct {
		result1 *pkg.Item
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 *pkg.Item
		result2 error
	}
	ReadStub        func(context.Context) (pkg.Items, error)
	readMutex       sync.RWMutex
	readArgsForCall []struct {
		arg1 context.Context
	}
	readReturns struct {
		result1 pkg.Items
		result2 error
	}
	readReturnsOnCall map[int]struct {
		result1 pkg.Items
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *RemoteAttentionStore) Answer(arg1 context.Context, arg2 pkg.ItemID, arg3 string, arg4 string, arg5 pkg.Decision, arg6 *pkg.Answer, arg7 pkg.Answers, arg8 *pkg.AnsweredClient) (*pkg.Item, error) {
	fake.answerMutex.Lock()
	ret, specificReturn := fake.answerReturnsOnCall[len(fake.answerArgsForCall)]
	fake.answerArgsForCall = append(fake.answerArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.ItemID
		arg3 string
		arg4 string
		arg5 pkg.Decision
		arg6 *pkg.Answer
		arg7 pkg.Answers
		arg8 *pkg.AnsweredClient
	}{arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8})
	stub := fake.AnswerStub
	fakeReturns := fake.answerReturns
	fake.recordInvocation("Answer", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8})
	fake.answerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *RemoteAttentionStore) AnswerCallCount() int {
	fake.answerMutex.RLock()
	defer fake.answerMutex.RUnlock()
	return len(fake.answerArgsForCall)
}

func (fake *RemoteAttentionStore) AnswerCalls(stub func(context.Context, pkg.ItemID, string, string, pkg.Decision, *pkg.Answer, pkg.Answers, *pkg.AnsweredClient) (*pkg.Item, error)) {
	fake.answerMutex.Lock()
	defer fake.answerMutex.Unlock()
	fake.AnswerStub = stub
}

func (fake *RemoteAttentionStore) AnswerArgsForCall(i int) (context.Context, pkg.ItemID, string, string, pkg.Decision, *pkg.Answer, pkg.Answers, *pkg.AnsweredClient) {
	fake.answerMutex.RLock()
	defer fake.answerMutex.RUnlock()
	argsForCall := fake.answerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6, argsForCall.arg7, argsForCall.arg8
}

func (fake *RemoteAttentionStore) AnswerReturns(result1 *pkg.Item, result2 error) {
	fake.answerMutex.Lock()
	defer fake.answerMutex.Unlock()
	fake.AnswerStub = nil
	fake.answerReturns = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *RemoteAttentionStore) AnswerReturnsOnCall(i int, result1 *pkg.Item, result2 error) {
	fake.answerMutex.Lock()
	defer fake.answerMutex.Unlock()
	fake.AnswerStub = nil
	if fake.answerReturnsOnCall == nil {
		fake.answerReturnsOnCall = make(map[int]struct {
			result1 *pkg.Item
			result2 error
		})
	}
	fake.answerReturnsOnCall[i] = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *RemoteAttentionStore) Close(arg1 context.Context, arg2 pkg.ItemID, arg3 string, arg4 *pkg.AnsweredClient) (*pkg.Item, error) {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.ItemID
		arg3 string
		arg4 *pkg.AnsweredClient
	}{arg1, arg2, arg3, arg4})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{arg1, arg2, arg3, arg4})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *RemoteAttentionStore) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *RemoteAttentionStore) CloseCalls(stub func(context.Context, pkg.ItemID, string, *pkg.AnsweredClient) (*pkg.Item, error)) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *RemoteAttentionStore) CloseArgsForCall(i int) (context.Context, pkg.ItemID, string, *pkg.AnsweredClient) {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	argsForCall := fake.closeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *RemoteAttentionStore) CloseReturns(result1 *pkg.Item, result2 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *RemoteAttentionStore) CloseReturnsOnCall(i int, result1 *pkg.Item, result2 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 *pkg.Item
			result2 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *RemoteAttentionStore) Escalate(arg1 context.Context, arg2 pkg.ItemID, arg3 string) (*pkg.Item, error) {
	fake.escalateMutex.Lock()
	ret, specificReturn := fake.escalateReturnsOnCall[len(fake.escalateArgsForCall)]
	fake.escalateArgsForCall = append(fake.escalateArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.ItemID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.EscalateStub
	fakeReturns := fake.escalateReturns
	fake.recordInvocation("Escalate", []interface{}{arg1, arg2, arg3})
	fake.escalateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *RemoteAttentionStore) EscalateCallCount() int {
	fake.escalateMutex.RLock()
	defer fake.escalateMutex.RUnlock()
	return len(fake.escalateArgsForCall)
}

func (fake *RemoteAttentionStore) EscalateCalls(stub func(context.Context, pkg.ItemID, string) (*pkg.Item, error)) {
	fake.escalateMutex.Lock()
	defer fake.escalateMutex.Unlock()
	fake.EscalateStub = stub
}

func (fake *RemoteAttentionStore) EscalateArgsForCall(i int) (context.Context, pkg.ItemID, string) {
	fake.escalateMutex.RLock()
	defer fake.escalateMutex.RUnlock()
	argsForCall := fake.escalateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *RemoteAttentionStore) EscalateReturns(result1 *pkg.Item, result2 error) {
	fake.escalateMutex.Lock()
	defer fake.escalateMutex.Unlock()
	fake.EscalateStub = nil
	fake.escalateReturns = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *RemoteAttentionStore) EscalateReturnsOnCall(i int, result1 *pkg.Item, result2 error) {
	fake.escalateMutex.Lock()
	defer fake.escalateMutex.Unlock()
	fake.EscalateStub = nil
	if fake.escalateReturnsOnCall == nil {
		fake.escalateReturnsOnCall = make(map[int]struct {
			result1 *pkg.Item
			result2 error
		})
	}
	fake.escalateReturnsOnCall[i] = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *RemoteAttentionStore) Get(arg1 context.Context, arg2 pkg.ItemID) (*pkg.Item, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.ItemID
	}{arg1, arg2})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1, arg2})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *RemoteAttentionStore) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *RemoteAttentionStore) GetCalls(stub func(context.Context, pkg.ItemID) (*pkg.Item, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *RemoteAttentionStore) GetArgsForCall(i int) (context.Context, pkg.ItemID) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *RemoteAttentionStore) GetReturns(result1 *pkg.Item, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *RemoteAttentionStore) GetReturnsOnCall(i int, result1 *pkg.Item, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *pkg.Item
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *pkg.Item
		result2 error
	}{result1, result2}
}

func (fake *RemoteAttentionStore) Read(arg1 context.Context) (pkg.Items, error) {
	fake.readMutex.Lock()
	ret, specificReturn := fake.readReturnsOnCall[len(fake.readArgsForCall)]
	fake.readArgsForCall = append(fake.readArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ReadStub
	fakeReturns := fake.readReturns
	fake.recordInvocation("Read", []interface{}{arg1})
	fake.readMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *RemoteAttentionStore) ReadCallCount() int {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	return len(fake.readArgsForCall)
}

func (fake *RemoteAttentionStore) ReadCalls(stub func(context.Context) (pkg.Items, error)) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = stub
}

func (fake *RemoteAttentionStore) ReadArgsForCall(i int) context.Context {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	argsForCall := fake.readArgsForCall[i]
	return argsForCall.arg1
}

func (fake *RemoteAttentionStore) ReadReturns(result1 pkg.Items, result2 error) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = nil
	fake.readReturns = struct {
		result1 pkg.Items
		result2 error
	}{result1, result2}
}

func (fake *RemoteAttentionStore) ReadReturnsOnCall(i int, result1 pkg.Items, result2 error) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = nil
	if fake.readReturnsOnCall == nil {
		fake.readReturnsOnCall = make(map[int]struct {
			result1 pkg.Items
			result2 error
		})
	}
	fake.readReturnsOnCall[i] = struct {
		result1 pkg.Items
		result2 error
	}{result1, result2}
}

func (fake *RemoteAttentionStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *RemoteAttentionStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.RemoteAttentionStore = new(RemoteAttentionStore)
