// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/attention-controller/pkg"
)

type SessionHeartbeatStore struct {
	GetStub        func(context.Context, string) (pkg.SessionHeartbeat, bool, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getReturns struct {
		result1 pkg.SessionHeartbeat
		result2 bool
		result3 error
	}
	getReturnsOnCall map[int]struct {
		result1 pkg.SessionHeartbeat
		result2 bool
		result3 error
	}
	ListStub        func(context.Context) (pkg.SessionHeartbeats, error)
	listMutex       sync.RWMutex
	listArgsForCall []struct {
		arg1 context.Context
	}
	listReturns struct {
		result1 pkg.SessionHeartbeats
		result2 error
	}
	listReturnsOnCall map[int]struct {
		result1 pkg.SessionHeartbeats
		result2 error
	}
	PostStub        func(context.Context, pkg.SessionHeartbeat) error
	postMutex       sync.RWMutex
	postArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.SessionHeartbeat
	}
	postReturns struct {
		result1 error
	}
	postReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *SessionHeartbeatStore) Get(arg1 context.Context, arg2 string) (pkg.SessionHeartbeat, bool, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1, arg2})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *SessionHeartbeatStore) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *SessionHeartbeatStore) GetCalls(stub func(context.Context, string) (pkg.SessionHeartbeat, bool, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *SessionHeartbeatStore) GetArgsForCall(i int) (context.Context, string) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *SessionHeartbeatStore) GetReturns(result1 pkg.SessionHeartbeat, result2 bool, result3 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 pkg.SessionHeartbeat
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *SessionHeartbeatStore) GetReturnsOnCall(i int, result1 pkg.SessionHeartbeat, result2 bool, result3 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 pkg.SessionHeartbeat
			result2 bool
			result3 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 pkg.SessionHeartbeat
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *SessionHeartbeatStore) List(arg1 context.Context) (pkg.SessionHeartbeats, error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListStub
	fakeReturns := fake.listReturns
	fake.recordInvocation("List", []interface{}{arg1})
	fake.listMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *SessionHeartbeatStore) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *SessionHeartbeatStore) ListCalls(stub func(context.Context) (pkg.SessionHeartbeats, error)) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *SessionHeartbeatStore) ListArgsForCall(i int) context.Context {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	argsForCall := fake.listArgsForCall[i]
	return argsForCall.arg1
}

func (fake *SessionHeartbeatStore) ListReturns(result1 pkg.SessionHeartbeats, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 pkg.SessionHeartbeats
		result2 error
	}{result1, result2}
}

func (fake *SessionHeartbeatStore) ListReturnsOnCall(i int, result1 pkg.SessionHeartbeats, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 pkg.SessionHeartbeats
			result2 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 pkg.SessionHeartbeats
		result2 error
	}{result1, result2}
}

func (fake *SessionHeartbeatStore) Post(arg1 context.Context, arg2 pkg.SessionHeartbeat) error {
	fake.postMutex.Lock()
	ret, specificReturn := fake.postReturnsOnCall[len(fake.postArgsForCall)]
	fake.postArgsForCall = append(fake.postArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.SessionHeartbeat
	}{arg1, arg2})
	stub := fake.PostStub
	fakeReturns := fake.postReturns
	fake.recordInvocation("Post", []interface{}{arg1, arg2})
	fake.postMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *SessionHeartbeatStore) PostCallCount() int {
	fake.postMutex.RLock()
	defer fake.postMutex.RUnlock()
	return len(fake.postArgsForCall)
}

func (fake *SessionHeartbeatStore) PostCalls(stub func(context.Context, pkg.SessionHeartbeat) error) {
	fake.postMutex.Lock()
	defer fake.postMutex.Unlock()
	fake.PostStub = stub
}

func (fake *SessionHeartbeatStore) PostArgsForCall(i int) (context.Context, pkg.SessionHeartbeat) {
	fake.postMutex.RLock()
	defer fake.postMutex.RUnlock()
	argsForCall := fake.postArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *SessionHeartbeatStore) PostReturns(result1 error) {
	fake.postMutex.Lock()
	defer fake.postMutex.Unlock()
	fake.PostStub = nil
	fake.postReturns = struct {
		result1 error
	}{result1}
}

func (fake *SessionHeartbeatStore) PostReturnsOnCall(i int, result1 error) {
	fake.postMutex.Lock()
	defer fake.postMutex.Unlock()
	fake.PostStub = nil
	if fake.postReturnsOnCall == nil {
		fake.postReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.postReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *SessionHeartbeatStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *SessionHeartbeatStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.SessionHeartbeatStore = new(SessionHeartbeatStore)
