// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/attention-controller/pkg"
)

type SessionLivenessChecker struct {
	IsLiveStub        func(context.Context, string) bool
	isLiveMutex       sync.RWMutex
	isLiveArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	isLiveReturns struct {
		result1 bool
	}
	isLiveReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *SessionLivenessChecker) IsLive(arg1 context.Context, arg2 string) bool {
	fake.isLiveMutex.Lock()
	ret, specificReturn := fake.isLiveReturnsOnCall[len(fake.isLiveArgsForCall)]
	fake.isLiveArgsForCall = append(fake.isLiveArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.IsLiveStub
	fakeReturns := fake.isLiveReturns
	fake.recordInvocation("IsLive", []interface{}{arg1, arg2})
	fake.isLiveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *SessionLivenessChecker) IsLiveCallCount() int {
	fake.isLiveMutex.RLock()
	defer fake.isLiveMutex.RUnlock()
	return len(fake.isLiveArgsForCall)
}

func (fake *SessionLivenessChecker) IsLiveCalls(stub func(context.Context, string) bool) {
	fake.isLiveMutex.Lock()
	defer fake.isLiveMutex.Unlock()
	fake.IsLiveStub = stub
}

func (fake *SessionLivenessChecker) IsLiveArgsForCall(i int) (context.Context, string) {
	fake.isLiveMutex.RLock()
	defer fake.isLiveMutex.RUnlock()
	argsForCall := fake.isLiveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *SessionLivenessChecker) IsLiveReturns(result1 bool) {
	fake.isLiveMutex.Lock()
	defer fake.isLiveMutex.Unlock()
	fake.IsLiveStub = nil
	fake.isLiveReturns = struct {
		result1 bool
	}{result1}
}

func (fake *SessionLivenessChecker) IsLiveReturnsOnCall(i int, result1 bool) {
	fake.isLiveMutex.Lock()
	defer fake.isLiveMutex.Unlock()
	fake.IsLiveStub = nil
	if fake.isLiveReturnsOnCall == nil {
		fake.isLiveReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isLiveReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *SessionLivenessChecker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *SessionLivenessChecker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.SessionLivenessChecker = new(SessionLivenessChecker)
