// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/attention-controller/pkg"
)

type TaskIndex struct {
	ApplyPathsStub        func(context.Context, []string)
	applyPathsMutex       sync.RWMutex
	applyPathsArgsForCall []struct {
		arg1 context.Context
		arg2 []string
	}
	LookupStub        func(string) (pkg.Task, bool)
	lookupMutex       sync.RWMutex
	lookupArgsForCall []struct {
		arg1 string
	}
	lookupReturns struct {
		result1 pkg.Task
		result2 bool
	}
	lookupReturnsOnCall map[int]struct {
		result1 pkg.Task
		result2 bool
	}
	ReconcileStub        func(context.Context)
	reconcileMutex       sync.RWMutex
	reconcileArgsForCall []struct {
		arg1 context.Context
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TaskIndex) ApplyPaths(arg1 context.Context, arg2 []string) {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.applyPathsMutex.Lock()
	fake.applyPathsArgsForCall = append(fake.applyPathsArgsForCall, struct {
		arg1 context.Context
		arg2 []string
	}{arg1, arg2Copy})
	stub := fake.ApplyPathsStub
	fake.recordInvocation("ApplyPaths", []interface{}{arg1, arg2Copy})
	fake.applyPathsMutex.Unlock()
	if stub != nil {
		fake.ApplyPathsStub(arg1, arg2)
	}
}

func (fake *TaskIndex) ApplyPathsCallCount() int {
	fake.applyPathsMutex.RLock()
	defer fake.applyPathsMutex.RUnlock()
	return len(fake.applyPathsArgsForCall)
}

func (fake *TaskIndex) ApplyPathsCalls(stub func(context.Context, []string)) {
	fake.applyPathsMutex.Lock()
	defer fake.applyPathsMutex.Unlock()
	fake.ApplyPathsStub = stub
}

func (fake *TaskIndex) ApplyPathsArgsForCall(i int) (context.Context, []string) {
	fake.applyPathsMutex.RLock()
	defer fake.applyPathsMutex.RUnlock()
	argsForCall := fake.applyPathsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TaskIndex) Lookup(arg1 string) (pkg.Task, bool) {
	fake.lookupMutex.Lock()
	ret, specificReturn := fake.lookupReturnsOnCall[len(fake.lookupArgsForCall)]
	fake.lookupArgsForCall = append(fake.lookupArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.LookupStub
	fakeReturns := fake.lookupReturns
	fake.recordInvocation("Lookup", []interface{}{arg1})
	fake.lookupMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TaskIndex) LookupCallCount() int {
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	return len(fake.lookupArgsForCall)
}

func (fake *TaskIndex) LookupCalls(stub func(string) (pkg.Task, bool)) {
	fake.lookupMutex.Lock()
	defer fake.lookupMutex.Unlock()
	fake.LookupStub = stub
}

func (fake *TaskIndex) LookupArgsForCall(i int) string {
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	argsForCall := fake.lookupArgsForCall[i]
	return argsForCall.arg1
}

func (fake *TaskIndex) LookupReturns(result1 pkg.Task, result2 bool) {
	fake.lookupMutex.Lock()
	defer fake.lookupMutex.Unlock()
	fake.LookupStub = nil
	fake.lookupReturns = struct {
		result1 pkg.Task
		result2 bool
	}{result1, result2}
}

func (fake *TaskIndex) LookupReturnsOnCall(i int, result1 pkg.Task, result2 bool) {
	fake.lookupMutex.Lock()
	defer fake.lookupMutex.Unlock()
	fake.LookupStub = nil
	if fake.lookupReturnsOnCall == nil {
		fake.lookupReturnsOnCall = make(map[int]struct {
			result1 pkg.Task
			result2 bool
		})
	}
	fake.lookupReturnsOnCall[i] = struct {
		result1 pkg.Task
		result2 bool
	}{result1, result2}
}

func (fake *TaskIndex) Reconcile(arg1 context.Context) {
	fake.reconcileMutex.Lock()
	fake.reconcileArgsForCall = append(fake.reconcileArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ReconcileStub
	fake.recordInvocation("Reconcile", []interface{}{arg1})
	fake.reconcileMutex.Unlock()
	if stub != nil {
		fake.ReconcileStub(arg1)
	}
}

func (fake *TaskIndex) ReconcileCallCount() int {
	fake.reconcileMutex.RLock()
	defer fake.reconcileMutex.RUnlock()
	return len(fake.reconcileArgsForCall)
}

func (fake *TaskIndex) ReconcileCalls(stub func(context.Context)) {
	fake.reconcileMutex.Lock()
	defer fake.reconcileMutex.Unlock()
	fake.ReconcileStub = stub
}

func (fake *TaskIndex) ReconcileArgsForCall(i int) context.Context {
	fake.reconcileMutex.RLock()
	defer fake.reconcileMutex.RUnlock()
	argsForCall := fake.reconcileArgsForCall[i]
	return argsForCall.arg1
}

func (fake *TaskIndex) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TaskIndex) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.TaskIndex = new(TaskIndex)
