// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/attention-controller/pkg"
)

type TaskIndex struct {
	LookupStub        func(string) (pkg.Task, bool)
	lookupMutex       sync.RWMutex
	lookupArgsForCall []struct {
		arg1 string
	}
	lookupReturns struct {
		result1 pkg.Task
		result2 bool
	}
	lookupReturnsOnCall map[int]struct {
		result1 pkg.Task
		result2 bool
	}
	RebuildStub        func(context.Context)
	rebuildMutex       sync.RWMutex
	rebuildArgsForCall []struct {
		arg1 context.Context
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TaskIndex) Lookup(arg1 string) (pkg.Task, bool) {
	fake.lookupMutex.Lock()
	ret, specificReturn := fake.lookupReturnsOnCall[len(fake.lookupArgsForCall)]
	fake.lookupArgsForCall = append(fake.lookupArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.LookupStub
	fakeReturns := fake.lookupReturns
	fake.recordInvocation("Lookup", []interface{}{arg1})
	fake.lookupMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TaskIndex) LookupCallCount() int {
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	return len(fake.lookupArgsForCall)
}

func (fake *TaskIndex) LookupCalls(stub func(string) (pkg.Task, bool)) {
	fake.lookupMutex.Lock()
	defer fake.lookupMutex.Unlock()
	fake.LookupStub = stub
}

func (fake *TaskIndex) LookupArgsForCall(i int) string {
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	argsForCall := fake.lookupArgsForCall[i]
	return argsForCall.arg1
}

func (fake *TaskIndex) LookupReturns(result1 pkg.Task, result2 bool) {
	fake.lookupMutex.Lock()
	defer fake.lookupMutex.Unlock()
	fake.LookupStub = nil
	fake.lookupReturns = struct {
		result1 pkg.Task
		result2 bool
	}{result1, result2}
}

func (fake *TaskIndex) LookupReturnsOnCall(i int, result1 pkg.Task, result2 bool) {
	fake.lookupMutex.Lock()
	defer fake.lookupMutex.Unlock()
	fake.LookupStub = nil
	if fake.lookupReturnsOnCall == nil {
		fake.lookupReturnsOnCall = make(map[int]struct {
			result1 pkg.Task
			result2 bool
		})
	}
	fake.lookupReturnsOnCall[i] = struct {
		result1 pkg.Task
		result2 bool
	}{result1, result2}
}

func (fake *TaskIndex) Rebuild(arg1 context.Context) {
	fake.rebuildMutex.Lock()
	fake.rebuildArgsForCall = append(fake.rebuildArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RebuildStub
	fake.recordInvocation("Rebuild", []interface{}{arg1})
	fake.rebuildMutex.Unlock()
	if stub != nil {
		fake.RebuildStub(arg1)
	}
}

func (fake *TaskIndex) RebuildCallCount() int {
	fake.rebuildMutex.RLock()
	defer fake.rebuildMutex.RUnlock()
	return len(fake.rebuildArgsForCall)
}

func (fake *TaskIndex) RebuildCalls(stub func(context.Context)) {
	fake.rebuildMutex.Lock()
	defer fake.rebuildMutex.Unlock()
	fake.RebuildStub = stub
}

func (fake *TaskIndex) RebuildArgsForCall(i int) context.Context {
	fake.rebuildMutex.RLock()
	defer fake.rebuildMutex.RUnlock()
	argsForCall := fake.rebuildArgsForCall[i]
	return argsForCall.arg1
}

func (fake *TaskIndex) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TaskIndex) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.TaskIndex = new(TaskIndex)
